apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
  {{- include "mongo-express.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: web
    {{- include "mongo-express.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: web
      {{- include "mongo-express.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              key: mongo-server
              name: mongo-config
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            configMapKeyRef:
              key: mongo-url
              name: mongo-config
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.mongoExpress.image.repository }}:{{ .Values.deployment.mongoExpress.image.tag
          | default .Chart.AppVersion }}
        name: mongo-express
        ports:
        - containerPort: 8081
        resources: {{- toYaml .Values.deployment.mongoExpress.resources | nindent 10 }}