apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
  {{- include "mongo-chart.labels" . | nindent 4 }}
data:
  mongo-password: {{ required "secret.mongoPassword is required" .Values.secret.mongoPassword | quote }}
  mongo-user: {{ required "secret.mongoUser is required" .Values.secret.mongoUser | quote }}
type: Opaque